#!/bin/bash -x

alias python=python3
alias act="oj t -c 'python3 main.py' -d ./tests/"
alias acs="acc s main.py -- --guess-python-interpreter pypy -w 0 -y"
alias cda="cd ../a"
alias cdb="cd ../b"
alias cdc="cd ../c"
alias cdd="cd ../d"
alias cde="cd ../e"
alias cdf="cd ../f"
alias cdg="cd ../g"
alias cats1="cat tests/sample-1.in | python main.py"
alias cats2="cat tests/sample-2.in | python main.py"
alias cats3="cat tests/sample-3.in | python main.py"
alias cats4="cat tests/sample-4.in | python main.py"

echo "---"
echo "---> source source.sh"
echo "---"
echo "alias python=python3"
echo "alias act='oj t -c 'python3 main.py' -d ./tests/'"
echo "alias acs='acc s main.py -- --guess-python-interpreter pypy -w 0 -y'"
echo alias cda="cd ../a"
echo alias cdb="cd ../b"
echo alias cdc="cd ../c"
echo alias cdd="cd ../d"
echo alias cde="cd ../e"
echo alias cdf="cd ../f"
echo alias cdg="cd ../g"

